/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "isr_timer.h"
#include "Button_Right_1_aliases.h"
#include "Button_Right_1.h"
#include "Button_Left_1_aliases.h"
#include "Button_Left_1.h"
#include "Button_Left_2_aliases.h"
#include "Button_Left_2.h"
#include "PWM_RGB_blue.h"
#include "UART_Logs.h"
#include "isr_buttons.h"
#include "Button_Right_2_aliases.h"
#include "Button_Right_2.h"
#include "ErikaOS_ee.h"
#include "ErikaOS_ee_tracing.h"
#include "Clock_Counter_RG.h"
#include "Counter.h"
#include "SEVEN_reg.h"
#include "SEVEN_SELECT_aliases.h"
#include "SEVEN_SELECT.h"
#include "SEVEN_DP_aliases.h"
#include "SEVEN_DP.h"
#include "SEVEN_G_aliases.h"
#include "SEVEN_G.h"
#include "SEVEN_F_aliases.h"
#include "SEVEN_F.h"
#include "SEVEN_E_aliases.h"
#include "SEVEN_E.h"
#include "SEVEN_D_aliases.h"
#include "SEVEN_D.h"
#include "SEVEN_C_aliases.h"
#include "SEVEN_C.h"
#include "SEVEN_B_aliases.h"
#include "SEVEN_B.h"
#include "SEVEN_A_aliases.h"
#include "SEVEN_A.h"
#include "led_red_aliases.h"
#include "led_red.h"
#include "led_yellow_aliases.h"
#include "led_yellow.h"
#include "led_green_aliases.h"
#include "led_green.h"
#include "PWM_led_red.h"
#include "PWM_led_yellow.h"
#include "PWM_led_green.h"
#include "Clock_PWM.h"
#include "PWM_RGB_green.h"
#include "PWM_RGB_red.h"
#include "RGB_blue_aliases.h"
#include "RGB_blue.h"
#include "RGB_green_aliases.h"
#include "RGB_green.h"
#include "RGB_red_aliases.h"
#include "RGB_red.h"
#include "UART_Logs_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

